apiVersion: apps/v1
kind: Deployment
metadata:
  name: johnmaria-eta-deploy
  labels:
    app: johnmaria-eta-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: johnmaria-eta-app
  template:
    metadata:
      labels:
        app: johnmaria-eta-app
    spec:
      containers:
      - name: johnmaria-eta-container
        image: johnmaria/health-care-webapp
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: johnmaria-eta-np-service
  labels:
    app: johnmaria-eta-app
spec:
  selector:
    app: johnmaria-eta-app

  type: NodePort
  ports:
  - nodePort: 31028
    port: 8082
    targetPort: 8082
